name: Maven Package WAR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Build with Maven
      run: mvn package --batch-mode --file pom.xml
    - name: Upload WAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: target/*.war
        
    - name: Deploy to Remote Server
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        scp: simple-java-maven-app/target/*.jar => /tmp/

    - name: Slack Notification on Success
      if: success()
      uses: slackapi/slack-github-action@v2.1.0
      with:
        slack-webhook-uri: ${{ secrets.SLACK_URL }}
        slack-message: |
          :tada: Build successful and WAR file transferred!
          To deploy to Tomcat, use the `/deploy` command in this channel.
          
    - name: Slack Notification on Failure
      if: failure()
      uses: slackapi/slack-github-action@v2.1.0
      with:
        slack-webhook-uri: ${{ secrets.SLACK_URL }}
        slack-message: ":cry: Build failed!"

# The Invoke Jenkins Deployment Job step is removed as Jenkins will be triggered directly from Slack
    
#    - name: Invoke Jenkins Deployment Job
#      uses: appleboy/jenkins-action@master
#      with: 
#        url: "http://65.1.168.148:8080"
#        user: "admin"
#        token:  ${{ secrets.MY_SECRET }} 
#        job: "Deploy2Tomcat"
