name: Java CI with Maven
on:
  push:
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  maven_build:
    strategy:
      matrix:
        version: [11, 8]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK "${{ matrix.version }}"
        uses: actions/setup-java@v3
        with:
          java-version: "${{ matrix.version }}"

          distribution: 'temurin'
          cache: maven      
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-cache
      - name: Build with Maven
        run: mvn -B package --file pom.xml

#      - name: scp ssh pieplines
#        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
#        with:
#          host: ${{ secrets.HOST }}
#          user: ${{ secrets.USERNAME }}
#          pass:  ${{ secrets.PASSWORD }}
#          port:  ${{ secrets.PORT }}
#          scp: | 
#            ./target/*.war => /tmp/
#          last_ssh: |
#            ls -lart /tmp

      - name: Invoke Jenkins Deployment Job
        uses: appleboy/jenkins-action@master
        with: 
          url: "http:172.31.27.232:8080"
          user: "admin"
          token:  ${{ secrets.JENKINS_TOKEN }} 
          job: "BuildthenDeploy"

          
