name: Maven Package WAR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Build with Maven
      run: mvn package --batch-mode --file pom.xml
    - name: Upload WAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: target/*.war
        
    - name: Deploy to Remote Server
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        scp: simple-java-maven-app/target/*.jar => /tmp/

    - name: Slack Notification on Success
      if: success()
      uses: slackapi/slack-github-action@v2.1.0
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        payload: |
          {
            "text": ":tada: Build successful and WAR file transferred!\nClick \"Approve\" to deploy to Tomcat.",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":tada: Build successful and WAR file transferred!\nThe WAR file has been placed in `/tmp/simple-java-maven-app/target/` on the Jenkins server.\nClick \"Approve\" to deploy to Tomcat."
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Approve",
                      "emoji": true
                    },
                    "style": "primary",
                    "value": "approve_deployment",
                    "action_id": "approve_button"
                  },
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Deny",
                      "emoji": true
                    },
                    "style": "danger",
                    "value": "deny_deployment",
                      "action_id": "deny_button"
                    }
                  ]
                }
              ]
            }
        errors: false
        payload-templated: false
        retries: 5
        
    - name: Slack Notification on Failure
      if: failure()
      uses: slackapi/slack-github-action@v2.1.0
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        payload: |
          {
            "text": ":cry: Build failed!"
          }
        errors: false
        payload-templated: false
        retries: 5
        
# The Invoke Jenkins Deployment Job step is removed as Jenkins will be triggered directly from Slack
    
#    - name: Invoke Jenkins Deployment Job
#      uses: appleboy/jenkins-action@master
#      with: 
#        url: "http://65.1.168.148:8080"
#        user: "admin"
#        token:  ${{ secrets.MY_SECRET }} 
#        job: "Deploy2Tomcat"
